[build]
  publish = "dist/"
  command = "apt-get install -y ncurses5-compat && mkdir bin && curl https://static.lamdera.com/bin/linux/lamdera -o ./bin/lamdera && chmod a+x ./bin/lamdera && ./bin/lamdera make src/Main.elm --output dist/index.html"
