[build]
  publish = "dist/"
  command = "mkdir bin && curl https://static.lamdera.com/bin/linux/lamdera -o ./bin/lamdera && chmod a+x ./bin/lamdera && lamdera make src/Main.elm --output dist/index.html"
